<%
'------------------------------------
dim aryTrade(31)	'行业列表
aryTrade(0) = "未知行业......"
aryTrade(1) = "计算机行业"
aryTrade(2) = "电器、电子、通讯设备"
aryTrade(3) = "科研设计、科技开发"
aryTrade(4) = "机电设备、产品"
aryTrade(5) = "仪器仪表、度量衡器"
aryTrade(6) = "机械制造及设备"
aryTrade(7) = "各种车辆制造与销售"
aryTrade(8) = "化学化工、生物制药"
aryTrade(9) = "五金矿产、金属制品"
aryTrade(10) = "纺织服装"
aryTrade(11) = "农林牧渔"
aryTrade(12) = "轻工"
aryTrade(13) = "房地产、建筑、安装、装潢"
aryTrade(14) = "造纸、印刷、包装"
aryTrade(15) = "木材家具"
aryTrade(16) = "广告、策划、设计"
aryTrade(17) = "新闻出版、广播电视"
aryTrade(18) = "信息咨询、事务所、人才交流"
aryTrade(19) = "金融、保险"
aryTrade(20) = "交通运输"
aryTrade(21) = "综合性工商企业"
aryTrade(22) = "市政、公用事业"
aryTrade(23) = "教育事业"
aryTrade(24) = "医疗、卫生事业"
aryTrade(25) = "文化艺术"
aryTrade(26) = "体育娱乐、办公用品"
aryTrade(27) = "日用生活服务"
aryTrade(28) = "商业服务"
aryTrade(29) = "物资供销"
aryTrade(30) = "饮食、旅游业"
aryTrade(31) = "粮油、副食"
'------------------------------------
%>