<!--#include file="conn.asp"-->
<!--#include file="pageset.asp"-->
<!--#include file="css.asp"-->

<table width="760" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr> 
    <td height="30"> </td>
  </tr>
  <tr> 
   
      <td height="200"> 
        <div align="center"> 
          <table border="0" cellspacing="0" cellpadding="0">
            <tr> 
              <td width="31"><img src="im/err.gif" ></td>
              <td width="10">&nbsp;</td>
              <td><b><%=session("err")%></b></td>
            </tr>
          </table>
          <p>
            <input type="button" name="Submit" value="·µ»Ø" onclick='history.back()'>
          </p>
        </div></td>

  </tr>
  <tr> 
    <td> 
      
    </td>
  </tr>
</table>
</body> 
