<!--#include file="conn.asp"-->
<!--#include file="pageset.asp"-->
<!--#include file="css.asp"-->
<table width="760" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr> 
    <td> <!--#include file="top.asp"--> </td>
  </tr>
  <tr> 
    <form name="form1" method="post" action="admin2.asp">
      <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>&nbsp;</td>
          </tr>
        </table> 
        <table width="500" height="108" border="0" align="center" cellpadding="0" cellspacing="0">
          <tr> 
            <td width="696" valign="top"> <center>
                <p><b>欢迎您的光临</b></p>
                </center>
              <ol>
                <li>要想留言请点“<img src="images/write.gif" width="15" height="14">&nbsp;<a href="write.asp">留言</a>”链接进入留言页面，其中主题最多可以输入25个字符，作者最多可以输入10个字符，留言内容最多可以输入10000个字符。另外点内容上面的图标“<img src="images/type_img.gif" width="13" height="16">&nbsp;<img src="images/type_url.gif" width="16" height="16">&nbsp;<img src="images/type_flash.gif" width="13" height="16">&nbsp;<img src="images/type_rm.gif" width="16" height="16">&nbsp;<img src="images/type_mp.gif" width="16" height="16">”分别可以在内容中插入“图片、链接、Flash、Real、Media”五种不同的媒体，完成后点“留言”页面会跳转到首页，就可以看到您的留言了。</li>
                <li>点“<img src="images/select.gif" width="15" height="15"> <a href="select.asp">查找</a>”就可以按您的条件找到您要的留言，其中作者必须准确输入，主题可以按关键字输入，查找结果会显示所有包含关键字的留言，留言数目显示在留言下面。</li>
                <li>首页按更新时间的顺序排序留言，留言前面的图标：<img src="images/new.gif" width="14" height="14">-表示今日的留言并没有回复；<img src="images/re.gif" width="14" height="14">-表示今日回复的留言；<img src="images/old.gif" width="14" height="14">-表示非今日的留言并且今日没有回复。留言后面的图标表示留言中包含的媒体。同时页面以固定的时间间隔刷新，保持您看到最新的信息。</li>
                <li>声明：您的留言不能有损于本留言板的利益，本留言板只是提供了一个留言的环境，您必须对自己的言论负责，若发现您的言论不当斑竹会屏蔽您的IP，您将在一定时间内不能再登录本留言板，谢谢您的合作。</li>
              </ol>
              </td>
          </tr>
        </table>
        
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>&nbsp;</td>
          </tr>
        </table></td>
    </form>
  </tr>
  <tr> 
    <td> 
      
    </td>
  </tr>
</table>
</body> 
</html>